-- DROP TABLES IF EXIST
DROP TABLE IF EXISTS user;

-- AUTHENTICATION
CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL, 
  userType TEXT NOT NULL
);